# wrangler.toml
name = "modern-m2labs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Build configuration for Cloudflare Pages
[build]
command = "npm run build && npx @cloudflare/next-on-pages"
cwd = "."

[build.environment]
NODE_VERSION = "22.16.0"