# wrangler.toml
name = "modern-m2labs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "m2labs-production"
database_id = "32c16743-49ee-4404-a091-bfbf0bb92c32"

# Cloudflare R2 Storage
[[r2_buckets]]
binding = "R2"
bucket_name = "m2labs-images"